### ISSUE TITLE
ToastActionsSnoozeAndDismiss does not work

### ISSUE THREAD

**Issue by srad123** [anbare/NotificationsExtensions#11]
The default ToastActionsSnoozeAndDismiss created by using "Actions = new ToastActionsSnoozeAndDismiss()" generates an xml node 
<actions hint-systemCommand="SnoozeAndDismiss"/>
which is incorrect. The corresponding notification will not show the Snooze and Dismiss buttons.
The correct xml is 
<actions hint-systemCommands=""SnoozeAndDismiss""/>
Notice and "s" at the end of hint-systemCommand

Please check the sample from Microsoft available at
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Notifications/cs/Notifications/ScenarioPages/Toasts/Actions/SystemCommands/SnoozeAndDismiss

**Comment by andrewleader** [comment]
Ah shoot, I was using our [co-worker's toast documentation](http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/02/adaptive-and-interactive-toast-notifications-for-windows-10.aspx) when writing NotificationsExtensions, which had this typo missing the "s" (just updated his article fixing that typo).

I'll fix this in NotificationsExtensions in a few hours, and I'll submit an updated NuGet package, the NuGet packages usually go live in a few hours. So by tomorrow this will be fixed!

Thanks for pointing out this issue!!

**Comment by andrewleader** [comment]
Fixed with commit: https://github.com/WindowsNotifications/NotificationsExtensions/commit/29f24b3d117b30d4b40b21f698044f5baf52ae0f

Will be uploading updated NuGet package in a few hours.

**Comment by srad123** [comment]
Thanks a lot for the prompt fix.
