### ISSUE TITLE
On Windows 10 Mobile DisplayName has no effect

### ISSUE THREAD

**Issue by balazs-adam** [anbare/NotificationsExtensions#12]
Hi,

I can't seem to override the default DisplayName (so my app's name appears) on my live tile on Windows 10 mobile. I tried to set the DisplayName property on the TileVisual and on the TileBinding object and it works fine on desktop but not on mobile. I know that there's a limitation on the branding attribute on mobile so it only supports the name or none branding but this page doesn't say anything similar on the displayname. 
https://msdn.microsoft.com/en-us/library/windows/apps/mt590880.aspx

I've also tried using the plain xml based approach with the same result so it's probably not a bug in the NotificationExtensions wrapper but here's my code, am I doing something wrong?

TileContent tile = new TileContent()
{
  Visual = new TileVisual
  {
    DisplayName = report.CameraName,
    Branding = TileBranding.Name,
    TileMedium = new TileBinding
    {
        Content = new TileBindingContentAdaptive
        {
          BackgroundImage = new TileBackgroundImage { Source = new TileImageSource(report.SquareSnapshotPath) },
        }
    },
    TileWide = new TileBinding
    {
       DisplayName = $"{report.CameraName} - {report.SnapshotTime.ToString("HH:mm")}",
       Branding = TileBranding.NameAndLogo,
       Content = new TileBindingContentAdaptive
       {
         BackgroundImage = new TileBackgroundImage { Source = new TileImageSource(report.WideSnapshotPath) },
       }
    },
    TileLarge = new TileBinding
    {
         DisplayName = $"{report.CameraName} - {report.SnapshotTime.ToString("HH:mm")}",
         Branding = TileBranding.NameAndLogo,
         Content = new TileBindingContentAdaptive
         {
           BackgroundImage = new TileBackgroundImage { Source = new TileImageSource(report.SquareSnapshotPath) },
         }
     }
  }
};

**Comment by andrewleader** [comment]
Hey Senkia, what build of Windows 10 Mobile are you running? Sounds like it's definitely a bug in Windows 10 Mobile since it works fine in Desktop, but I'd be happy to investigate the bug and see whether it's already been addressed.

**Comment by balazs-adam** [comment]
I'm using version 1511, build 10586.29 on mobile and version 1511, build 10586.71 on desktop.

**Comment by balazs-adam** [comment]
It's also strange that the built in weather app seems to use the displayname to show the current location and it works fine. I've also tried hiding the displayname and using a simple tile text instead but the tile's built-in padding makes it out of line from the other tile's names.

**Comment by andrewleader** [comment]
Hmm yeah, the Weather app uses displayName, so if it works there, it should be working for you too. I can't repro this issue on the latest builds, I'm trying the older 10586 builds and looking through old bugs to see if we fixed anything around this.

**Comment by andrewleader** [comment]
Ohh, I think I might know what's going wrong...
1. Is this for your primary tile?
2. Are you using the ShortName property in your app's manifest?

Mobile has a bug where, if ShortName is specified on the base tile, the displayName provided by the tile notification will not work (the ShortName is always displayed).

Workaround is to not use the ShortName property on your primary tile (open the Package.appxmanifest with the visual editor, select the Visual Assets tab, and on All Image Assets, make sure the "Short name" text box is blank)

**Comment by balazs-adam** [comment]
Thanks! That did solve my problem.
