### ISSUE TITLE
Image placement attribute case

### ISSUE THREAD

**Issue by artemshuba** [anbare/NotificationsExtensions#14]
I noticed some strange behavior with image placement attribute. I updated my old project to use NotificationsExtensions library instead of an old AdaptiveExtensions and found that the tile looks different now.
Previously it looked like this:
![](http://i.imgur.com/qv5ljJy.png)
After moving to NotificationsExtensions it now looks like this:
![](http://i.imgur.com/PTYLt4R.png) ![](http://i.imgur.com/HVi65p7.png)

So I looked at the generated xml for tile:

``` xml
<tile>
    <visual>
        <binding template="TileMedium" branding="none">
            <image src="ms-appdata:///local/ImageCache/264492.png" placement="peek"/>
            <text>Under the Dome</text>
            <text hint-style="captionSubtle" hint-wrap="true">S01E01 Pilot</text>
        </binding>
        <binding template="TileWide" branding="none">
            <image src="ms-appdata:///local/ImageCache/264492.png" placement="peek"/>
            <text>Under the Dome</text>
            <text hint-style="captionSubtle" hint-wrap="true">S01E01 Pilot</text>
        </binding>
    </visual>
</tile>
```

... and notices that it uses lowercase value for image placement attribute. But if I change it to "Peek":

``` xml
<image src="ms-appdata:///local/ImageCache/264492.png" placement="Peek"/>
```

... it becomes looking like on the first picture.
I checked it on Windows 10 10586.104.

**Comment by andrewleader** [comment]
The behavior you're seeing in NotificationsExtensions is correct.

What you were seeing in AdaptiveExtensions was an incorrect behavior. The correct value is lowercase "peek".

The peek image is supposed to animate like your second example does, as you can see from the following GIF
![image](http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-01-71-81-adaptive_2D00_tile_2D00_templates/4572.PeekTile.gif)

Start has never intentionally supported displaying a half image like your first example. That's a bug, not the intended behavior.
