### ISSUE TITLE
group and subgroup in ToastVisual

### ISSUE THREAD

**Issue by nguyenquyhy** [anbare/NotificationsExtensions#19]
Is there plan to add group and subgroup to support adaptive toast template?

**Comment by andrewleader** [comment]
Yep, we'll be adding it soon. We still haven't finalized and published the toast schema yet, hence why we haven't updated Extensions.

**Comment by andrewleader** [comment]
Group and subgroup has been added to toast notifications with commit 1f1168a25bca70e1d3dfeb4392c79d0f419f1373! More info here: https://blogs.msdn.microsoft.com/tiles_and_toasts/2016/05/23/notificationsextensions-updated-for-anniversary-update-of-windows-10/
