### ISSUE TITLE
ToastNotification could not be found

### ISSUE THREAD

**Issue by samsamm777** [anbare/NotificationsExtensions#23]
Ive installed via Nuget. However i cannot find the ToastNotification class.

**Comment by andrewleader** [comment]
Hey Sam, sounds like you added NotificationsExtensions to either a web project or a portable class library.

ToastNotification is a WinRT class, it will only be available if you're writing code in a UWP project or library.

Therefore, you can use the GetContent method to obtain the XML of the notification as a string

```
string xml = content.GetContent();
```

And then, if you're sending push notifications, you use that xml string for the HTTP body. If you're using it in a portable class library that your UWP consumes, you'll have to return that xml string and then create an XmlDocument from it and construct the ToastNotification in your UWP project.

**Comment by samsamm777** [comment]
@anbare thanks for the clarification. Im building a winforms application, so im guessing thats why the references arnt available. I'll have to look into a UWP application then it seems.
