### ISSUE TITLE
NotificationMate?

### ISSUE THREAD

**Issue by AzureKitsune** [anbare/NotificationsExtensions#26]
Is NotificationMate's functionality still going to be released? I can't seem to find it in the latest stable on Nuget. (Version: 14332.0.1)

**Comment by matthidinger** [comment]
We are still putting it through some additional testing before moving to master. You can find it in the separate branch though, and please let us know if you find any issues!

**Comment by AzureKitsune** [comment]
I'll definitely put it through its paces! Thanks!
