### ISSUE TITLE
Bug in Windows 10.0.14393.x with Live Tiles !

### ISSUE THREAD

**Issue by CordoWEB** [anbare/NotificationsExtensions#29]
Bug in Windows 10.0.14393.x with Live Tiles !

When you pin a Live Tile with local images ... all is fine :)
When you pin a Live Tile with online images ... the content is not update :(

Verified with my own app ... and Notification Visualizer.

On Windows Mobile 10.0.14393.x i have an other bug ... the Live Tiles are not updated after a certain time :(

**Comment by andrewleader** [comment]
Hey Cordo, can you include the XML of your tile that is using online images? I'm not seeing any issues on 14393 with online images on my laptop (and it worked on my Lumia 950 too).

**Comment by CordoWEB** [comment]
I have the issue on 3 computers with the XML code of the Notifications Visualzer App :

``<tile>
  <visual branding="name">

    <binding template="TileMedium">
      <text hint-style="caption">Fable: Legends</text>
      <text hint-style="captionSubtle">Level 7</text>
      <text hint-style="captionSubtle">5 friends playing</text>
    </binding>

    <binding template="TileWide">
      <group>
        <subgroup hint-weight="33">
          <image src="http://binged.it/1aYCfS8" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Resume Playing</text>
          <text hint-style="captionSubtle">Level 7</text>
          <text hint-style="captionSubtle">5 friends playing</text>
        </subgroup>
      </group>

      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Halo: Spartan Strike</text>
          <text hint-style="captionSubtle">Level 2</text>
          <text hint-style="captionSubtle">3 friends playing</text>
        </subgroup>
      </group>
    </binding>

    <binding template="TileLarge">

      <group>
        <subgroup hint-weight="33">
          <image src="http://binged.it/1aYCfS8" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Resume Playing</text>
          <text hint-style="captionSubtle">Level 7</text>
          <text hint-style="captionSubtle">5 friends playing</text>
        </subgroup>
      </group>

      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Halo: Spartan Strike</text>
          <text hint-style="captionSubtle">Level 2</text>
          <text hint-style="captionSubtle">3 friends playing</text>
        </subgroup>
      </group>

      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Forza 4</text>
          <text hint-style="captionSubtle">Level 4</text>
          <text hint-style="captionSubtle">2 friends playing</text>
        </subgroup>
      </group>

    </binding>

  </visual>
</tile>


For information i use french version of Windows.

**Comment by CordoWEB** [comment]
I have the issue on 3 computers with the XML code of the Notifications Visualzer App

`
<tile>
  <visual branding="name">
    <binding template="TileMedium">
      <text hint-style="caption">Fable: Legends</text>
      <text hint-style="captionSubtle">Level 7</text>
      <text hint-style="captionSubtle">5 friends playing</text>
    </binding>
    <binding template="TileWide">
      <group>
        <subgroup hint-weight="33">
          <image src="http://binged.it/1aYCfS8" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Resume Playing</text>
          <text hint-style="captionSubtle">Level 7</text>
          <text hint-style="captionSubtle">5 friends playing</text>
        </subgroup>
      </group>
      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Halo: Spartan Strike</text>
          <text hint-style="captionSubtle">Level 2</text>
          <text hint-style="captionSubtle">3 friends playing</text>
        </subgroup>
      </group>
    </binding>
    <binding template="TileLarge">
      <group>
        <subgroup hint-weight="33">
          <image src="http://binged.it/1aYCfS8" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Resume Playing</text>
          <text hint-style="captionSubtle">Level 7</text>
          <text hint-style="captionSubtle">5 friends playing</text>
        </subgroup>
      </group>
      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Halo: Spartan Strike</text>
          <text hint-style="captionSubtle">Level 2</text>
          <text hint-style="captionSubtle">3 friends playing</text>
        </subgroup>
      </group>
      <group>
        <subgroup hint-weight="33">
          <image src="http://bit.ly/1z1zEmb" />
        </subgroup>
        <subgroup>
          <text hint-style="body">Forza 4</text>
          <text hint-style="captionSubtle">Level 4</text>
          <text hint-style="captionSubtle">2 friends playing</text>
        </subgroup>
      </group>
    </binding>
  </visual>
</tile>`

With this code the tiles with images are not updates. When i replace images sources with "Assets/Apps/Hipstame/hipster.jpg" all is done.

For information i use french version of Windows.

**Comment by CordoWEB** [comment]
I have installed "MSN News" on my PC to test the live tile and it is not updated. After 3 hours only the default tile is displayed :(

**Comment by andrewleader** [comment]
Hmm, let me ask our dev team if there's any logs that we can have you grab to find out what's going wrong on your machine. Thanks for letting us know about the issue, I'll report back when I have something for you to try!

**Comment by andrewleader** [comment]
Oh one follow up question, do you use an internet proxy?

**Comment by CordoWEB** [comment]
Thanks a lot for your answer :)
I do not use Internet Proxy and i have this issue on three differents computers (Windows Pro 10.0.14393.67 French).

**Comment by CordoWEB** [comment]
I have reinstalled one of my computer from scratch and now all seems to be fine on it.
Do not loose your precious time with that issue ;)
