### ISSUE TITLE
ToastImage lacks hint-crop

### ISSUE THREAD

**Issue by nguyenquyhy** [anbare/NotificationsExtensions#3]

**Comment by nguyenquyhy** [comment]
Probably this is expected as toast will ignore that property anyway. Non-issue here I think.
However, I really hope that the toast messages will respect this attribute soon as hint-crop="circle" is possible in tiles.

**Comment by andrewleader** [comment]
Yeah, right now toasts only support hint-crop on the AppLogo (which the Notifications API supports). Inline images don't support it as you said.

Once that support is added to inline images, I'll update the API to allow it. I'm imagining toasts will someday be like adaptive tiles, and support the full range of adaptive syntax, which at that point a lot of things will have to change about the toast API.
