### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ArchieCoder** [anbare/NotificationsExtensions#6]
Hello,

Thanks for creating the updated version for Windows 10.

Please include the license in this project. It you can add the link in the nuget license field it would be very good too.

It might be irrelevant for indie developers but the current client that I work on takes very seriously on how we copy code from the web. For the previous version of the NotificationsExtensions from Microsoft, we needed to remove the Nuget NotificationsExtensions and uses the code from the MSDN sample where the license was included!

Thanks

**Comment by andrewleader** [comment]
The license was already here in the root folder: https://github.com/anbare/NotificationsExtensions/blob/master/LICENSE

Does it need to be included in every single project? This is the first open source code I've published, so please tell me if I'm doing anything wrong.

The next new package I submit to NuGet will have the license URL. Thanks for catching that!!

**Comment by ArchieCoder** [comment]
The way that you added the license in the root project is perfect. Yes, you should add it to all of your projects as a good practice especially if you post on behalf of Microsoft.

Thanks!

**Comment by andrewleader** [comment]
Awesome, I just added it to all the projects. Thanks!
