### ISSUE TITLE
Setters for Inputs and Buttons in ToastActionCustom

### ISSUE THREAD

**Issue by nguyenquyhy** [anbare/NotificationsExtensions#7]
Currently Inputs and Buttons properties in ToastActionCustom do not have a setter, which prevents users from declaring the list directly while initializing the object.
Something like this is not possible at the moment:

``` CSharp
new ToastActionCustom
{
    Inputs = new List<IToastInput> { new ToastTextBox("response") }
}
```

May I know if there is any reason for the limitation?

**Comment by andrewleader** [comment]
The syntax for object initializing is...

``` CSharp
new ToastActionsCustom()
{
    Inputs =
    {
        new ToastTextBox("myId")
    }
};
```

That's the same pattern as controls like StackPanel (which for Children, is get-only). My co-worker Matt showed me that cool syntax for initializing get-only lists inside the object initializer, which is super cool! The code samples on this GitHub's Wiki use the above syntax in the examples, hopefully teaching people that this feature of C# exists.

There's a bug with IntelliSense where it doesn't suggest the "Inputs" property though, which makes it a little difficult to discover the properties unfortunately. We've notified the Visual Studio team about it.

Btw, I just learned how to do C# syntax highlighting on GitHub thanks to you!!!
